services:
  # Backend - Laravel
  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/backend:/var/www
    depends_on:
      - db
    networks:
      - app-network

  # Base de datos MySQL
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: laravelDosRuedas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root

    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Frontend - Angular
  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/frontend:/app
    command: npm start -- --host 0.0.0.0
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
